### ISSUE TITLE
Time does not reset upon sleeping

### ISSUE THREAD

**Issue by cantorsdust** [cantorsdust/FreezeInside#1]
Placeholder to remind me to bug Zoryn to update the API.

**Comment by cantorsdust** [comment]
Fixed!

**Comment by SsapS** [comment]
I am getting this once a week or so in game.  Usually right at 12am-1210 from what I can gather, but doesn't always happen.  Its right when the comment boxes saying 'its getting late..." start appearing.

Which just starts looping when you go into your house to sleep.

Freeze inside 1.4.4.1
SV 1.05

**Comment by cantorsdust** [comment]
I can reproduce if I go in the house at exactly 12, when LetMachinesRunWhileTimeFrozen is true.  I suspect that what's happening is that the comment box is set to fire every 10 minute tick when it's 12am.  And since time is frozen at 12am...

Using LetMachinesRunWhileTimeFrozen = false will prevent this, as it prevents new time ticks from actually occurring.  If it really bothers you, change to that.  Otherwise, this is an unavoidable interaction between the specific 12am event and my workaround for getting machines to run while time is paused.

Sorry, not broken / won't fix.

**Comment by SsapS** [comment]
Nah man I wasn't attacking your work or anything, just came to see if this had been reported and share my experience.

edit: happened the night of the meteor crash at 11pm as well
edit2: didnt realize this the first 5-6 times this happened, but reloading the game starts the day correctly.
